#ifndef __ARCH_X86_DEFS_H
#define __ARCH_X86_DEFS_H

#define OFFSET_REG_GS	20
#define OFFSET_REG_FS	24
#define OFFSET_REG_ES	28
#define OFFSET_REG_DS	32
#define OFFSET_REG_EDI	36
#define OFFSET_REG_ESI	40
#define OFFSET_REG_EBP	44
#define OFFSET_REG_ESP	48
#define OFFSET_REG_EBX	52
#define OFFSET_REG_EDX	56
#define OFFSET_REG_ECX	60
#define OFFSET_REG_EAX	64
#define OFFSET_REG_EIP	76

#endif
